// <auto-generated />
namespace DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MrKupido20130104a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MrKupido20130104a));
        
        string IMigrationMetadata.Id
        {
            get { return "201301041552473_MrKupido-20130104a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
