// <auto-generated />
namespace DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MrKupido20130218a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MrKupido20130218a));
        
        string IMigrationMetadata.Id
        {
            get { return "201302190026539_MrKupido-20130218a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
