// <auto-generated />
namespace DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MrKupido_20130315a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MrKupido_20130315a));
        
        string IMigrationMetadata.Id
        {
            get { return "201303151758330_MrKupido_20130315a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
