// <auto-generated />
namespace DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MrKupido20130218b : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MrKupido20130218b));
        
        string IMigrationMetadata.Id
        {
            get { return "201302190127320_MrKupido-20130218b"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
