//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrKupido.Web.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TipsAndTricks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipsAndTricks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MrKupido.Web.Resources.Shared.TipsAndTricks", typeof(TipsAndTricks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q&lt;a href=\&quot;./hun/account/profile\&quot;&gt;Szeretnéd, ha személyre szabott porciókat ajánlanánk? Add meg a magasságod, súlyod és életkorod! &gt;&gt;&lt;/a&gt;.
        /// </summary>
        public static string TipsAndTricks0 {
            get {
                return ResourceManager.GetString("TipsAndTricks0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSzűrőket használva leegyszerűsíthetjük a keresést. Próbálkozz hozzávalóval, diétával vagy az étel nevével..
        /// </summary>
        public static string TipsAndTricks1 {
            get {
                return ResourceManager.GetString("TipsAndTricks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAz F11 billentyű megnyomásával teljes képernyős módba válthatsz, amivel még tovább növelheted szemeid esztétikai kényeztetését!.
        /// </summary>
        public static string TipsAndTricks10 {
            get {
                return ResourceManager.GetString("TipsAndTricks10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q&lt;a href=\&quot;http://mrkupido.uservoice.com\&quot;&gt;Van jó ötleted, hogy mivel tehetnénk jobbá az oldalt? Látogass el az ötletadó oldalunkra &gt;&gt;&lt;/a&gt;.
        /// </summary>
        public static string TipsAndTricks11 {
            get {
                return ResourceManager.GetString("TipsAndTricks11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BA PAGE-UP, PAGE-DOWN, HOME, END és kurzor billenyűkkel is tudsz lapozni..
        /// </summary>
        public static string TipsAndTricks2 {
            get {
                return ResourceManager.GetString("TipsAndTricks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHa keresési feltételt szeretnél törölni, akkor azt a DEL (első) vagy BACKSPACE (utolsó elem) lenyomávásal is megteheted..
        /// </summary>
        public static string TipsAndTricks3 {
            get {
                return ResourceManager.GetString("TipsAndTricks3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHa a helyszín hibásan jelenik meg, akkor az azért van, mert nem mobilról vagy WiFi-n keresztül csatlakoztál..
        /// </summary>
        public static string TipsAndTricks4 {
            get {
                return ResourceManager.GetString("TipsAndTricks4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMinden véleményt szívesen várunk, amit egyszerűen és gyorsan a jobb lenti sarokban tudsz nekünk elküldeni..
        /// </summary>
        public static string TipsAndTricks5 {
            get {
                return ResourceManager.GetString("TipsAndTricks5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAmikor Mr. Kupido rántottát csinál, a tojások könyörögnek, hogy őket válasszák..
        /// </summary>
        public static string TipsAndTricks6 {
            get {
                return ResourceManager.GetString("TipsAndTricks6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMr. Kupidónak be sem kell dugnia a turmixgépet, mert a turmixgép örömében magától beindul..
        /// </summary>
        public static string TipsAndTricks7 {
            get {
                return ResourceManager.GetString("TipsAndTricks7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMr. Kupidónak sosem kell asztalt foglalnia egy étteremben, az étteremnek kell lefoglalnia Mr. Kupidót..
        /// </summary>
        public static string TipsAndTricks8 {
            get {
                return ResourceManager.GetString("TipsAndTricks8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EA receptek által okozott anyagi és emésztési károkért az oldal készítői nem vállalnak felelőséget!.
        /// </summary>
        public static string TipsAndTricks9 {
            get {
                return ResourceManager.GetString("TipsAndTricks9", resourceCulture);
            }
        }
    }
}
