//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrKupido.Web.Resources.Recipe {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Details {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Details() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MrKupido.Web.Resources.Recipe.Details", typeof(Details).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (with {0} helpers).
        /// </summary>
        public static string ChefNumber {
            get {
                return ResourceManager.GetString("ChefNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (alone).
        /// </summary>
        public static string ChefNumberOne {
            get {
                return ResourceManager.GetString("ChefNumberOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        public static string Directions {
            get {
                return ResourceManager.GetString("Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} tools missing).
        /// </summary>
        public static string EquipmentMissing {
            get {
                return ResourceManager.GetString("EquipmentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (you have all the tools).
        /// </summary>
        public static string EquipmentMissingZero {
            get {
                return ResourceManager.GetString("EquipmentMissingZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary equipment.
        /// </summary>
        public static string NecessaryEquipment {
            get {
                return ResourceManager.GetString("NecessaryEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrition table for one.
        /// </summary>
        public static string NutritionList {
            get {
                return ResourceManager.GetString("NutritionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (detailed).
        /// </summary>
        public static string NutritionListDetailed {
            get {
                return ResourceManager.GetString("NutritionListDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (simple).
        /// </summary>
        public static string NutritionListSimple {
            get {
                return ResourceManager.GetString("NutritionListSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe details.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (for {0} people).
        /// </summary>
        public static string PortionHint {
            get {
                return ResourceManager.GetString("PortionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (for you).
        /// </summary>
        public static string PortionHintOne {
            get {
                return ResourceManager.GetString("PortionHintOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving.
        /// </summary>
        public static string Serving {
            get {
                return ResourceManager.GetString("Serving", resourceCulture);
            }
        }
    }
}
