branches:
  only:
  - master

assembly_info:
  patch: false

configuration: Release

platform: Any CPU
  
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
before_build:
  - dotnet restore "src\GeoCoordinate.NetStandard1" -v Minimal

build_script:
  - dotnet build "src\GeoCoordinate.NetStandard1" -c %CONFIGURATION% --no-dependencies
  
after_build:
  - dotnet pack "src\GeoCoordinate.NetStandard1" -c %CONFIGURATION% --no-build -o artifacts
  
artifacts:
  - path: src\GeoCoordinate.NetStandard1\artifacts\*.nupkg